const exam2025_II_A = [
    // ==========================================
    // RAZONAMIENTO MATEMÁTICO (Q1 - Q10)
    // ==========================================
    { "numero": 1, "curso": "Razonamiento Matemático", "enunciado": "Dadas las siguientes premisas:\n- Todas las enfermeras trabajan en un hospital.\n- Algunas enfermeras son geriatras.\nSe concluye que:", "opciones": { "a": "Algunas geriatras no trabajan en un hospital.", "b": "Todas las geriatras trabajan en un hospital.", "c": "Algunas geriatras trabajan en un hospital.", "d": "Todas las que trabajan en un hospital son enfermeras.", "e": "Todas las geriatras son enfermeras." }, "correcta": "c" },
    { "numero": 2, "curso": "Razonamiento Matemático", "enunciado": "A una reunión asistieron 6 personas: Max, Óscar, Vladi, Sonia, Lucía y María. Óscar salió con la amiga de Lucía. Sonia, quien no simpatiza con Lucía, salió antes que Max. ¿Quién acompañó a María y con quién salió Max?", "opciones": { "a": "Óscar - Lucía", "b": "Óscar - Sonia", "c": "Vladi - Lucía", "d": "Vladi - Sonia", "e": "Max - María" }, "correcta": "b" },
    { "numero": 3, "curso": "Razonamiento Matemático", "enunciado": "La familia Hurtado tiene 5 hijos varones, cada hijo tiene una hermana y cada hermano tiene 2 sobrinas. ¿Cuál es el número mínimo de personas que conforman la familia Hurtado?", "opciones": { "a": "18", "b": "16", "c": "14", "d": "10", "e": "20" }, "correcta": "d" },
    { "numero": 4, "curso": "Razonamiento Matemático", "enunciado": "Si un cerdo pesa 50 kg más que 1/3 del peso de una oveja y la oveja pesa 15 kg más que 1/4 del peso del cerdo, ¿cuánto pesan los dos animales juntos?", "opciones": { "a": "100 kg", "b": "90 kg", "c": "60 kg", "d": "120 kg", "e": "97 kg" }, "correcta": "e" },
    { "numero": 5, "curso": "Razonamiento Matemático", "enunciado": "Leslie va al mercado; el doble del dinero que tiene es menor que S/ 32. Si al llegar compra una lechuga a S/ 2, entonces el triple de lo que le resta es mayor que S/ 36, ¿cuánto dinero tenía inicialmente?", "opciones": { "a": "S/ 14", "b": "S/ 16", "c": "S/ 10", "d": "S/ 20", "e": "S/ 15" }, "correcta": "e" },
    { "numero": 6, "curso": "Razonamiento Matemático", "enunciado": "Se define en el conjunto R según la figura adjunta. Calcule M.", "imagen": "images/2025_2_q6.png", "opciones": { "a": "1", "b": "2", "c": "4", "d": "3", "e": "5" }, "correcta": "b" },
    { "numero": 7, "curso": "Razonamiento Matemático", "enunciado": "Marcelino compra un caramelo y le regalan uno. Segunda vez compra 3 y le regalan 2; tercera vez compra 6 y le regalan 3; cuarta vez compra 10 y le regalan 4. ¿Cuántos caramelos recibirá en total luego de comprar por vigésima vez?", "opciones": { "a": "210", "b": "250", "c": "300", "d": "230", "e": "327" }, "correcta": "d" },
    { "numero": 8, "curso": "Razonamiento Matemático", "enunciado": "Halle el valor de 'S' en la serie mostrada en la imagen:", "imagen": "images/2025_2_q8.png", "opciones": { "a": "12/25", "b": "24/25", "c": "13/50", "d": "17/50", "e": "23/41" }, "correcta": "c" },
    { "numero": 9, "curso": "Razonamiento Matemático", "enunciado": "Determine el número de formas de leer la palabra UNASAM en la siguiente figura:", "imagen": "images/2025_2_q9.png", "opciones": { "a": "16", "b": "26", "c": "64", "d": "32", "e": "128" }, "correcta": "d" },
    { "numero": 10, "curso": "Razonamiento Matemático", "enunciado": "Si Shanty tiene las dos piezas de cartón que se muestran, ¿cuál de las figuras representa la unión de ambas?", "imagen": "images/2025_2_q10.png", "opciones": { "a": "Figura a", "b": "Figura b", "c": "Figura c", "d": "Figura d", "e": "Figura e" }, "correcta": "d" },

    // ==========================================
    // RAZONAMIENTO VERBAL (Q11 - Q20)
    // ==========================================
    { "numero": 11, "curso": "Razonamiento Verbal", "texto_contexto": "El cactus San Pedro (Trichocereus pachanoi) se encuentra generalmente en los Andes... Se puede ubicar en estado salvaje y también cultivado por la mano del hombre.", "enunciado": "¿Cuál de las siguientes acciones es MENOS adecuada para identificar el sentido de 'estado salvaje'?", "opciones": { "a": "Buscar definiciones en el diccionario.", "b": "Elaborar un cuadro comparativo para elegir el más frondoso.", "c": "Preguntar por qué se menciona 'cultivado por el hombre' después.", "d": "Buscar acepciones de ambas palabras.", "e": "Sustituir por una expresión equivalente." }, "correcta": "b" },
    { "numero": 12, "curso": "Razonamiento Verbal", "enunciado": "¿Cuál de las acciones se centra en obtener información implícita sobre los usos y creencias?", "opciones": { "a": "Narrar asociación con maleficios.", "b": "Mencionar la sustancia psicoactiva.", "c": "Señalar el tipo de ceremonias.", "d": "Detallar qué parte se usa en rituales.", "e": "Indicar la creencia popular de regalarlo al nacer un niño." }, "correcta": "e" },
    { "numero": 16, "curso": "Razonamiento Verbal", "enunciado": "PLAN DE REDACCIÓN: 'Educación con perspectiva de género'.\nI. Desafíos\nII. Importancia\nIII. Principios\nIV. Ejemplos\nV. Rol de docentes", "opciones": { "a": "II-III-I-V-IV", "b": "III-V-II-I-IV", "c": "III-I-V-IV-II", "d": "III-II-V-I-IV", "e": "V-II-I-III-IV" }, "correcta": "d" },
    { "numero": 18, "curso": "Razonamiento Verbal", "enunciado": "CONECTORES: La universidad incrementó las becas estudiantiles, _______ redujo el presupuesto de investigación _______ afrontar la crisis.", "opciones": { "a": "aunque - por", "b": "pero - con el fin de", "c": "sin embargo - debido a que", "d": "y - a causa de", "e": "no obstante - con que" }, "correcta": "b" },
    { "numero": 19, "curso": "Razonamiento Verbal", "enunciado": "SINONIMIA CONTEXTUAL: 'La EFÍMERA naturaleza de la fama dificulta su APREHENSIÓN'.", "opciones": { "a": "breve - captura", "b": "temporal - asimilación", "c": "pasajera - retención", "d": "fugaz - entendimiento", "e": "instantánea - comprensión" }, "correcta": "c" },

    // ==========================================
    // MATEMÁTICA (Q21 - Q50)
    // ==========================================
    { "numero": 21, "curso": "Matemática", "enunciado": "Celular muestra: 'Si activas el GPS entonces podrás usar el mapa'. ¿Qué mensaje hace FALSA la proposición?", "opciones": { "a": "Activaste y usaste.", "b": "No activaste y no usaste.", "c": "Activaste y NO pudiste usar.", "d": "No activaste pero usaste.", "e": "Activaste y usaste otra app." }, "correcta": "c" },
    { "numero": 23, "curso": "Matemática", "enunciado": "La dirección de memoria 2F(16) en hexadecimal, equivale en sistema binario a:", "opciones": { "a": "101111", "b": "101011", "c": "101101", "d": "101110", "e": "101001" }, "correcta": "a" },
    { "numero": 24, "curso": "Matemática", "enunciado": "Máquina A produce pieza cada 48s, máquina B cada 72s. Si inician a las 07:00, ¿a qué hora coincidirán por TERCERA vez?", "opciones": { "a": "7h 4m 48s", "b": "7h 2m 24s", "c": "7h 7m 12s", "d": "7h 6m 12s", "e": "7h 8m 36s" }, "correcta": "c" },
    { "numero": 28, "curso": "Matemática", "enunciado": "Si f(t) = -2t² + 24t + 48 representa liebres contagiadas, determine en cuántos días se contagió la MAYOR cantidad.", "opciones": { "a": "15", "b": "8", "c": "9", "d": "12", "e": "6" }, "correcta": "e" },
    { "numero": 30, "curso": "Matemática", "enunciado": "C(t) = A * e^(-Bt). Halle el tiempo para que la cantidad inicial de bacterias se reduzca en un 50%.", "opciones": { "a": "ln2 / B", "b": "-B / ln2", "c": "B * ln2", "d": "(B/ln2)²", "e": "2B * ln2" }, "correcta": "a" },
    { "numero": 31, "curso": "Matemática", "enunciado": "Tachos verdes y blancos son 5 veces los marrones. Verdes son el triple de marrones. Blancos y marrones suman 123. Halle total de verdes y marrones.", "opciones": { "a": "123 y 82", "b": "41 y 82", "c": "123 y 41", "d": "82 y 164", "e": "164 y 41" }, "correcta": "c" },
    { "numero": 35, "curso": "Matemática", "enunciado": "En la figura, BC es diámetro, AB=BC y AM=MC. Halle x.", "imagen": "images/2025_2_q35.png", "opciones": { "a": "30°", "b": "24°", "c": "45°", "d": "36°", "e": "53/2°" }, "correcta": "d" },
    { "numero": 38, "curso": "Matemática", "enunciado": "Marco de ventana triangular con vidrio cuadrado. Determine el precio si 1m² cuesta 4 soles.", "imagen": "images/2025_2_q38.png", "opciones": { "a": "28 soles", "b": "32 soles", "c": "16 soles", "d": "36 soles", "e": "42 soles" }, "correcta": "b" },

    // ==========================================
    // FÍSICA (Q51 - Q60)
    // ==========================================
    { "numero": 51, "curso": "Física", "enunciado": "Vector A = 2i - 3j + 4k y vector B en un cubo de arista 2. Calcule módulo de A + B.", "imagen": "images/2025_2_q51.png", "opciones": { "a": "sqrt(21)", "b": "sqrt(41)", "c": "2*sqrt(3)", "d": "2*sqrt(5)", "e": "3*sqrt(2)" }, "correcta": "a" },
    { "numero": 52, "curso": "Física", "enunciado": "Calcule el módulo de la fuerza resultante de la figura:", "imagen": "images/2025_2_q52.png", "opciones": { "a": "25 N", "b": "28 N", "c": "20 N", "d": "30 N", "e": "24 N" }, "correcta": "e" },
    { "numero": 53, "curso": "Física", "enunciado": "Dos ciclistas en pista de 200m. A hacia B a 90km/h y B hacia A a 15m/s. ¿A qué distancia del poste se encontrarán?", "imagen": "images/2025_2_q53.png", "opciones": { "a": "5m derecha", "b": "5m izquierda", "c": "10m derecha", "d": "10m izquierda", "e": "3m derecha" }, "correcta": "b" },
    { "numero": 54, "curso": "Física", "enunciado": "Alcance máximo es 100m desde altura h. Halle alcance si altura es 2h.", "opciones": { "a": "100*sqrt(3)", "b": "200m", "c": "200*sqrt(2)", "d": "100*sqrt(2)", "e": "200*sqrt(3)" }, "correcta": "d" },
    { "numero": 58, "curso": "Física", "enunciado": "Cuerpo de 150N y 2000kg/m³ sumergido en agua. Determine la tensión T.", "imagen": "images/2025_2_q58.png", "opciones": { "a": "80 N", "b": "65 N", "c": "75 N", "d": "70 N", "e": "85 N" }, "correcta": "c" },

    // ==========================================
    // QUÍMICA (Q61 - Q70)
    // ==========================================
    { "numero": 61, "curso": "Química", "enunciado": "Identifique cuáles son cambios químicos:\nI. Ennegrecimiento de azúcar\nII. Formación de hielo\nIII. Evaporación de gasolina\nIV. Oxidación de un clavo", "opciones": { "a": "I y IV", "b": "II y IV", "c": "II y III", "d": "I y II", "e": "III y IV" }, "correcta": "a" },
    { "numero": 62, "curso": "Química", "enunciado": "Elemento con Z=17 y A=35 está formado por:", "opciones": { "a": "17p y 35n", "b": "17n y 18e", "c": "18e y 35p", "d": "17p y 18n", "e": "52p y 18n" }, "correcta": "d" },
    { "numero": 66, "curso": "Química", "enunciado": "Halle moles en 480g de MgSO4. (Mg=24, S=32, O=16)", "opciones": { "a": "1,33", "b": "2,5", "c": "0,25", "d": "4,0", "e": "3,25" }, "correcta": "d" },
    { "numero": 68, "curso": "Química", "enunciado": "Globo de 0,6L a 1 atm. Sube a 10km donde la presión es 0,4 atm. Halle volumen final.", "opciones": { "a": "3,0 L", "b": "0,4 L", "c": "1,5 L", "d": "0,9 L", "e": "2,4 L" }, "correcta": "c" },

    // ==========================================
    // CIENCIAS SOCIALES Y COMUNICACIÓN (Q71 - Q80)
    // ==========================================
    { "numero": 71, "curso": "Ciencias Sociales", "enunciado": "¿A qué área de la geografía le compete resolver la degradación de recursos y qué enfoque usaría?", "opciones": { "a": "Humana - Funcionalista", "b": "Económica - Problémico", "c": "Física - Enotecnológico", "d": "Ambiental - Sistémico", "e": "Cultural - Estructuralista" }, "correcta": "d" },
    { "numero": 74, "curso": "Ciencias Sociales", "enunciado": "Bancos realizan cobros sin informar. ¿A qué entidad acudir en primera instancia?", "opciones": { "a": "INDECOPI", "b": "SBS", "c": "Al mismo banco", "d": "SUNAT", "e": "Contraloría" }, "correcta": "c" },
    { "numero": 76, "curso": "Comunicación", "enunciado": "¿Qué oración interrumpe la progresión temática en el texto sobre celulares?", "opciones": { "a": "5", "b": "3", "c": "2", "d": "4", "e": "1" }, "correcta": "d" },
    { "numero": 79, "curso": "Comunicación", "enunciado": "Alternativa con verbo conjugado INCORRECTAMENTE:", "opciones": { "a": "El cantar es bueno.", "b": "Ojalá estuviera disponible.", "c": "Ya sabes, nadie sabe.", "d": "En plena lluvia, andé por las calles.", "e": "Había diez ciempiés." }, "correcta": "d" },
    { "numero": 80, "curso": "Comunicación", "enunciado": "Oración que requiere MAYÚSCULA inicial en la palabra resaltada:", "opciones": { "a": "humanismo", "b": "física", "c": "cordillera", "d": "alcalde", "e": "vía láctea" }, "correcta": "e" }
];